# Generated by Django 5.1.3 on 2024-11-27 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название области')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название склада')),
                ('location', models.TextField(blank=True, null=True, verbose_name='Местоположение')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название сектора')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='warehouse.area', verbose_name='Область')),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название полки')),
                ('surface', models.CharField(choices=[('lower', 'Нижняя'), ('middle', 'Средняя'), ('upper', 'Верхняя'), ('front', 'Поверхность')], max_length=10, verbose_name='Полка')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='warehouse.sector', verbose_name='Сектор')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='warehouse.warehouse', verbose_name='Склад'),
        ),
    ]
