"""
Django settings for sm_project project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

from django.template.context_processors import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3r!_q*1nghu80_fqu=kq@a1!dkl*(bbpl1qqujfo&_2ffcg5&m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['sme.kz','www.sme.kz','185.129.49.151','localhost']


def show_toolbar(request):
    return False


DEBUG_TOOLBAR_CONFIG = {
    "SHOW_TOOLBAR_CALLBACK": show_toolbar,
}
# Application definition

INSTALLED_APPS = [
    "unfold",  # before django.contrib.admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    "unfold.contrib.simple_history",  # optional, if django-simple-history package is used
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "debug_toolbar",
    'warehouse',
    'crm',
    'orders',
    'trucks',
    "simple_history",
    'import_export',
    'qr_handler',
    'orders.templatetags',
]

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

ROOT_URLCONF = 'sm_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sm_project.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'smp',  # Имя базы данных
        'USER': 'admin',  # Имя пользователя
        'PASSWORD': '123456789',  # Пароль пользователя
        'HOST': 'localhost',  # Хост, где работает PostgreSQL
        'PORT': '5432',  # Порт PostgreSQL
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# STATIC (для файлов CSS, JS и других статических ресурсов)
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # Дополнительные папки с файлами
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Путь для сбора файлов (например, для продакшена)

# MEDIA (для загруженных пользователем файлов)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Папка для хранения загруженных файлов

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# https://docs.djangoproject.com/en/5.1/ref/settings/#date-input-formats
DATE_INPUT_FORMATS = [
    "%d.%m.%Y",  # Custom input
    "%Y-%m-%d",  # '2006-10-25'
    "%m/%d/%Y",  # '10/25/2006'
    "%m/%d/%y",  # '10/25/06'
    "%b %d %Y",  # 'Oct 25 2006'
    "%b %d, %Y",  # 'Oct 25, 2006'
    "%d %b %Y",  # '25 Oct 2006'
    "%d %b, %Y",  # '25 Oct, 2006'
    "%B %d %Y",  # 'October 25 2006'
    "%B %d, %Y",  # 'October 25, 2006'
    "%d %B %Y",  # '25 October 2006'
    "%d %B, %Y",  # '25 October, 2006'
]

# https://docs.djangoproject.com/en/5.1/ref/settings/#datetime-input-formats
DATETIME_INPUT_FORMATS = [
    "%d.%m.%Y %H:%M:%S",  # Custom input
    "%Y-%m-%d %H:%M:%S",  # '2006-10-25 14:30:59'
    "%Y-%m-%d %H:%M:%S.%f",  # '2006-10-25 14:30:59.000200'
    "%Y-%m-%d %H:%M",  # '2006-10-25 14:30'
    "%m/%d/%Y %H:%M:%S",  # '10/25/2006 14:30:59'
    "%m/%d/%Y %H:%M:%S.%f",  # '10/25/2006 14:30:59.000200'
    "%m/%d/%Y %H:%M",  # '10/25/2006 14:30'
    "%m/%d/%y %H:%M:%S",  # '10/25/06 14:30:59'
    "%m/%d/%y %H:%M:%S.%f",  # '10/25/06 14:30:59.000200'
    "%m/%d/%y %H:%M",  # '10/25/06 14:30'
]

# Для использования Pillow
OPTIMIZED_IMAGE_METHOD = 'pillow'


# STORAGES = {
#     "default": {
#         "BACKEND": "django.core.files.storage.FileSystemStorage",
#     },
#     "staticfiles": {
#         "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
#     },
# }
######################################################################
# Unfold
######################################################################

def permission_callback(request):
    return request.user.has_perm("orders.view_order")


UNFOLD = {
    "SITE_HEADER": "Saule-Marat",
    "SITE_TITLE": "Saule-Marat",
    "SITE_SYMBOL": "local_shipping",
    "DASHBOARD_CALLBACK": "qr_handler.utils.dashboard_callback",
    "SHOW_HISTORY": True,
    "LOGIN": {
        "image": lambda request: static("admin/images/login-bg.jpg"),
    },
    # "STYLES": [
    #     lambda request: static("admin/css/styles.css"),
    # ],
    "TABS": [
        {
            "models": ["orders.order"],
            "items": [
                {
                    "title": _("Все заказы"),
                    "icon": "assignment",
                    "link": reverse_lazy("admin:orders_order_changelist"),
                },
                {
                    "title": _("Принятые"),
                    "icon": "assignment_turned_in",
                    "link": lambda request: f"{reverse_lazy('admin:orders_order_changelist')}?status=accepted",
                },
                {
                    "title": _("Погрузка"),
                    "icon": "local_shipping",
                    "link": lambda request: f"{reverse_lazy('admin:orders_order_changelist')}?status=loading",
                },
                {
                    "title": _("В пути"),
                    "icon": "directions_car",
                    "link": lambda request: f"{reverse_lazy('admin:orders_order_changelist')}?status=in_transit",
                },
                {
                    "title": _("Выгрузка"),
                    "icon": "warehouse",
                    "link": lambda request: f"{reverse_lazy('admin:orders_order_changelist')}?status=unloading",
                },
                {
                    "title": _("На складе"),
                    "icon": "warehouse",
                    "link": lambda request: f"{reverse_lazy('admin:orders_order_changelist')}?status=in_warehouse",
                },
                {
                    "title": _("Выданные"),
                    "icon": "check_circle",
                    "link": lambda request: f"{reverse_lazy('admin:orders_order_changelist')}?status=completed",
                },
                {
                    "title": _("Отменённые"),
                    "icon": "cancel",
                    "link": lambda request: f"{reverse_lazy('admin:orders_order_changelist')}?status=canceled",
                },
                {
                    "title": _("Возврат"),
                    "icon": "keyboard_return",
                    "link": lambda request: f"{reverse_lazy('admin:orders_order_changelist')}?status=return",
                },
            ],
        },
    ],

    "SIDEBAR": {
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("Меню"),
                "items": [
                    {
                        "title": _("Главная"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                    {
                        "title": _("Заказы"),
                        "icon": "list_alt",
                        "link": reverse_lazy("admin:orders_order_changelist"),
                    },
                    {
                        "title": _("Клиенты"),
                        "icon": "badge",
                        "link": reverse_lazy("admin:crm_client_changelist"),
                    },
                ],
            },
            {
                "title": _("Фуры и Маршруты"),
                "collapsible": False,
                "items": [
                    {
                        "title": _("Маршруты"),
                        "icon": "route",
                        "link": reverse_lazy("admin:trucks_route_changelist"),
                    },
                    {
                        "title": _("Фуры"),
                        "icon": "local_shipping",
                        "link": reverse_lazy("admin:trucks_truck_changelist"),
                    },
                ],
            },
            {
                "title": _("Хранение"),
                "collapsible": False,
                "items": [
                    {
                        "title": _("Полки"),
                        "icon": "shelves",
                        "link": reverse_lazy("admin:warehouse_shelf_changelist"),
                    },
                    {
                        "title": _("Секторы"),
                        "icon": "shelf_position",
                        "link": reverse_lazy("admin:warehouse_sector_changelist"),
                    },
                    {
                        "title": _("Области"),
                        "icon": "view_comfy_alt",
                        "link": reverse_lazy("admin:warehouse_area_changelist"),
                    },
                    {
                        "title": _("Склады"),
                        "icon": "warehouse",
                        "link": reverse_lazy("admin:warehouse_warehouse_changelist"),
                    },

                ],
            },
            {
                "title": _("QR"),
                "collapsible": False,
                "items": [
                    {
                        "title": _("Добавить на полку"),
                        "icon": "qr_code_2_add",
                        "link": reverse_lazy("admin:add_orders_to_shelf_qr"),
                    },
                    {
                        "title": _("Информация по QR"),
                        "icon": "qr_code_2",
                        "link": reverse_lazy("admin:info_qr"),
                    },
                ],
            },
            {
                "title": _("Юзеры и Группы"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Юзеры"),
                        "icon": "person",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": _("Группы"),
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
        ]
    },
}
